//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionScheduleTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistributionScheduleTable()
        {
            this.ShoppingCardTables = new HashSet<ShoppingCardTable>();
        }
    
        public int ID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.TimeSpan StartingDeliveryHour { get; set; }
        public System.TimeSpan EndingDeliveryHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCardTable> ShoppingCardTables { get; set; }
    }
}
